### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by steven7673** [MatKlucznyk/Qsys#12]
There seems to be a memory leak with the module. If I comment out the ParseInternalResponse method in the ResponseQueueDequeue method, it seems to stop.

**Comment by MatKlucznyk** [comment]
I noticed this as well. I’m in the middle of refactoring most of the classes and implementing more efficient parsing.

Mat

**Comment by MatKlucznyk** [comment]
I dont really want to call the GC if I dont have to so instead of processing each response I decided to check that the change object actually has a change in it before parsing it to a JObject. Basically what you suggested.

I'll leave this open for a bit before deeming it closed.
