### ISSUE TITLE
Re-connection issue if program started before QSC is booted.

### ISSUE THREAD

**Issue by GravelSlayer** [MatKlucznyk/Qsys#13]
First off great modules and thanks!

So what I found is that if a processor(cp4) is powered up and programs are running and then the QSC is powered up afterwards the module connects but then disconnects and reconnects non stop.  Works as normal after the program is restarted.  Rebooting QSC also has no effect on this condition.  See pic.

If the processor and QSC are booted up together or the processor after the QSC is booted then no issues at all.  Loading a qsc update or rebooting the QSC after the processor has been connected reconnects and is solid.  Even disconnecting power from the QSC and repowing at a later time also is fine. 

Using the latest cp4 firmware, qsc 110f with 9.4.2 and code from the master branch as of today.  

![Reconnect Issue](https://user-images.githubusercontent.com/107517546/173709095-a058cb13-35ea-4b0b-9019-a6b9ef769da2.png)

**Comment by MatKlucznyk** [comment]
To confirm, you are using the modules from the SIMPL folder or from the release zip?

Can you replicate this in emulator mode? If so can you please email me mathew.klucznyk@gmail.com with the Q-SYS file that this is occurring with.

**Comment by steven7673** [comment]
This looks like the issue #8 that I submitted weeks ago. It was marked as closed though, so I am am not sure if it's the same, but I was able to correct the issue as explained in issue #8

**Comment by GravelSlayer** [comment]
Ok this was an issue on my part.  Heavily tested and everything is rock solid.
