### ISSUE TITLE
HID Conferencing Phone Mute

### ISSUE THREAD

**Issue by MikeBrennan6466** [MatKlucznyk/Qsys#20]
Does one of your modules allow for this functionality with the Crestron modules to toggle the phone mute in the HID conferencing block?  Would the component name be the script name with phonemute eg. HID_Conferencing_IOUSB-1406PhoneMute using the Boolean named control?

**Comment by MatKlucznyk** [comment]
There is no specific component module for that block. I would add the Phone Mute control as a named control. The name you assign to the control in the Named Controls property window is the one you would use with the "Generic Boolean Named Control" module.

![image](https://github.com/MatKlucznyk/Qsys/assets/9019861/c2579857-a3a8-4379-8c6b-765619548f01)
