### ISSUE TITLE
Issues with some modules

### ISSUE THREAD

**Issue by mikaeljay** [MatKlucznyk/Qsys#21]
The Camera module works great and has been a great time saver.  Having issues with other modules though.  Just started building a system that needs a dialer for VoIP.  The softphone controller module keypad buttons do not seem to work.  I just went to generic triggers and that worked and then added a generic string control for the dial string and the compile came back with:

ERROR  (LGSPLS1009)  File: ** C:\Program Files (x86)\Crestron\Simpl\Usrsplus\Qsys Generic String Named Control.usp, Line 46
        Qsys Generic String Named Control.usp : Class or Structure does not contain member: 'NEWNAMEDCONTROLCHANGE'
ERROR  (LGCMCVT247)  
        Compile errors exist for SIMPL+, could not perform SIMPL+ link for C:\Program Files (x86)\Crestron\Simpl\Programs\WSBA\SPlsWork\Qsys_Generic_String_Named_Control.dll.

I've occassionally had the Fader module just seem to stop working, while the Camera module just goes like a champ.

Any thoughts?

**Comment by MatKlucznyk** [comment]
Are you using a release version or the current master branch modules?

**Comment by MatKlucznyk** [comment]
I'll take a look at the release version. In the interim, please give the main branch modules a go. In the SIMPL folder, there is a test program that you can extract the compiled modules from.

**Comment by mikaeljay** [comment]
Threw the main branch modules into the program folder (not user) and compile works.  I must have a mismatch between versions within the USR folders or something like that.   The softphone keypad buttons still do not generate JSON.  however.  Connect/disconnect do.

 

Thank you for your time and efforts.

**Comment by MatKlucznyk** [comment]
No problem, the Softphone keypad doesn’t actually generate a command until either you trigger connect or the softphone is currently connected.

**Comment by mikaeljay** [comment]
That’s what I was starting to think.  

 

Thank you again.

 

Michael
