### ISSUE TITLE
Core UMC and USP files are set to hidden from Symbol Library

### ISSUE THREAD

**Issue by muzicman82** [MatKlucznyk/Qsys#33]
Spent a bit of time trying to figure out why the Core modules weren't showing up in the Symbol Library. Last place I looked was the category or hidden status since the previous v2.4 version had them in there. Is there a reason they are set to hidden?

**Comment by MatKlucznyk** [comment]
The USP is hidden because its wrapped by the UMC. The UMC should not be hidden.

**Comment by muzicman82** [comment]
Nice, thanks!
