### ISSUE TITLE
Named Control cannot get feedback after reconnect to QSC server

### ISSUE THREAD

**Issue by winghoing** [MatKlucznyk/Qsys#4]
If I disconnect the crestron processor from the QSC processor and connect to QSC processor again, the qsc named control module cannot get the feedback from the qsc processor

**Comment by MatKlucznyk** [comment]
I'm not experiencing this issue. What generic module are you using for this named control and what component/control are you trying to control with it?

Also, are you using the modules from the SIMPL folder or are you using a release?

**Comment by winghoing** [comment]
I used "Qsys Generic Boolean Named Control" module and "Qsys Generic Integer Named Control" module in "Qsys.v2.2.0.zip".
I runned my own qsc program in emulator mode.
The steps to trigger this problem:
1. Once crestron processor is connected to qsc program, all operations are normal.
2. I make the qsc program to stop the emulator mode, wait a minute and start the emulator mode again.
3. I test the functions again, all functions are executed, but no feedbacks return.

**Comment by MatKlucznyk** [comment]
I can't replicate the issue with the most current modules. Please try the modules in the SIMPL folder and with Q-SYS Designer 9.3.

**Comment by winghoing** [comment]
I updated Q-SYS Designer to v9.3, it is ok now. Thanks for help

**Comment by winghoing** [comment]
I finally replicate the problem again, and record it as a video clip, in this link, https://1drv.ms/v/s!ArUHl7uRmLfghE2CZipOSteqyKy2
Please notice the "LG1FlexRouterO1I1_Selected_Fb" - "LG1FlexRouterO1I9_Selected_Fb" in the toolbox

**Comment by MatKlucznyk** [comment]
I just added a fix that I hope also solves your issue. Give it a try and let me know.

**Comment by winghoing** [comment]
The problem seems to be solved. I can't replicate the problem now. Thanks for your help.
