### ISSUE TITLE
SIMPL module won't initialize when PrimaryCoreIpAddress input is set on program load

### ISSUE THREAD

**Issue by rod-driscoll** [MatKlucznyk/Qsys#42]
In the SIMPL module "QSys Core.umc", if you enter the [PrimaryCoreIpAddress] at program load (using an SIO with a 1 on the input) then the device never initializes.
The issue is in the S+ module "QSys Core.usp" Main function, where the variables are set to values of the parameter inputs after "WaitForInitializationComplete", so if any of those variables are set to the inputs on the first SIMPL logic wave then the function will override them with the default parameters.
The solution is to put start Main in "QSys Core.usp" like below:
```
Function Main()
{    
	WaitForInitializationComplete();
	
	if(Port)			_port = Port;
	else				_port = Default_Port;
	if(len(PrimaryIpAddress)) 	_primaryIpa = PrimaryIpAddress;
	else 				_primaryIpa = Default_PrimaryIpAddress;
	if(len(BackupIpAddress)) 	_backupIpa = BackupIpAddress;
	else 				_backupIpa = Default_BackupIpAddress;
	if(len(Username)) 		_username = Username;
	else 				_username = Default_Username;
	if(len(Password)) 		_password = Password;
	else 				_password = Default_Password;

```
also to be safe do the same when any of those inputs are changed as follows:
```
change Port
{
	if(Port)	_port = Port;
	else		_port = Default_Port;
	processor.Port = _port;
}

change PrimaryIpAddress
{
	if(len(PrimaryIpAddress)) 	_primaryIpa = PrimaryIpAddress;
	else 				_primaryIpa = Default_PrimaryIpAddress;
	processor.PrimaryHost = _primaryIpa;
}

change BackupIpAddress
{
	if(len(BackupIpAddress)) 	_backupIpa = BackupIpAddress;
	else 				_backupIpa = Default_BackupIpAddress;
	processor.BackupHost = _backupIpa;
}
```

**Comment by MatKlucznyk** [comment]
@rod-driscoll Im not going to lie. I start everything with a one shot lol

Good catch! I'll implement this shortly.
