### ISSUE TITLE
Connecting with Username/Password

### ISSUE THREAD

**Issue by steven7673** [MatKlucznyk/Qsys#8]
To make it work in simpl sharp Pro with a Username and Password, I had to change line 384 of QsysCore to  
if (returnString.Contains("{\"jsonrpc\":\"2.0\",\"result\":true,\"id\":\"crestron\"}"))

If ''='' is used instead of contains, it connects but does not go passed that line

**Comment by MatKlucznyk** [comment]
I wasnt able to re-create this issue. Was it tested on a live core or emulator? What version of designer was used?

During my test using designer v9.4.0, in emulator mode, login was successful.

**Comment by steven7673** [comment]
It was on  live core, with version 9.4, I did not test in emulation mode.

Did you create your user in Q-Sys Administrator?

With Debug set to debug(2), I could see the response "{\"jsonrpc\":\"2.0\",\"result\":true,\"id\":\"crestron\"}" in console
But it did not go past this, basically not triggering your 5 second timer for your init method.

Got it working by changing it to
if (returnString.Contains("{\"jsonrpc\":\"2.0\",\"result\":true,\"id\":\"crestron\"}"))

Let me know if you find something else.

Thanks



De : Mat Klucznyk ***@***.***>
Envoyé : 23 avril 2022 07:52
À : MatKlucznyk/Qsys ***@***.***>
Cc : Steven Gauthier ***@***.***>; Author ***@***.***>
Objet : Re: [MatKlucznyk/Qsys] Connecting with Username/Password (Issue #8)


I wasnt able to re-create this issue. Was it tested on a live core or emulator? What version of designer was used?

During my test using designer v9.4.0, in emulator mode, login was successful.
